Update docs + S3 bucket pictures
OpenBB-finance/openbb-docs pull request #32
Opened 2024-10-15 16:22 UTC by IgorWounds

^

2024-10-19 04:29 UTC, DidierRLopes requested changes
Can we keep the attachment files on copilot please?

2024-10-19 12:02 UTC, IgorWounds commented
> Can we keep the attachment files on copilot please?

@mnicstruwig

2024-10-21 09:25 UTC, mnicstruwig commented
> > Can we keep the attachment files on copilot please?
> 
> @mnicstruwig

@DidierRLopes, this is something we removed to simplify the user workflow. Everyone we showed this to was in agreement / didn't have objections.

Especially now that users have drag-and-drop to "dashboard" functionality for files, everything becomes a lot cleaner: the dashboard is the "data lake" for OpenBB Copilot.

2024-10-21 09:39 UTC, mnicstruwig requested changes
Couple of tweaks / changes.

2024-10-21 09:39 UTC, mnicstruwig commented on content/pro/openbb-copilot.md
> +OpenBB Copilot can also analyze and answer questions using files you provide, such as TXT, PDF, CSV, and XLSX files. To upload a file, click the blue plus icon in the lower right part of your dashboa
```suggestion
OpenBB Copilot can also analyze and answer questions using files you provide, such as PDF, CSV, and XLSX files. To add a file to OpenBB Copilot, first [add it to the currently-active dashboard](<link for adding files to Terminal>).
```

Currently TXT isn't supported by the front-end for widgets.

2024-10-21 09:39 UTC, mnicstruwig commented on content/pro/openbb-copilot.md
> +Once you've uploaded a file, it will become a widget on your dashboard that you can interact with.
```suggestion
Once the file widget has been added to your dashboard, you can add it to OpenBB Copilot explicitly by clicking the "add widget to context" button, or you can simply begin querying, and OpenBB Copilot will retrieve the data if it is relevant to your query.
```

2024-10-21 09:39 UTC, mnicstruwig commented on content/pro/openbb-copilot.md
> +OpenBB Copilot can use the data from these widget files to answer your questions. If it does, it will cite the specific files (for PDFs, the exact page) it referenced.
```suggestion
If OpenBB Copilot uses your file widget to answer any part of you query, it will show citations after its answer.
```

2024-10-21 10:11 UTC, mnicstruwig approved these changes
TY, LGTM.

2024-10-22 00:31 UTC, DidierRLopes commented
> > > Can we keep the attachment files on copilot please?
> > 
> > 
> > @mnicstruwig
> 
> @DidierRLopes, this is something we removed to simplify the user workflow. Everyone we showed this to was in agreement / didn't have objections, because of how it removed confusion for users.
> 
> Especially now that users have drag-and-drop to "dashboard" functionality for files, everything becomes a lot cleaner: the dashboard is the "data lake" for OpenBB Copilot. Everything is now a widget, without special differences between user files and backends. This is a "clarity" win.
> 
> When you could add files in multiple ways to Copilot, it was very confusing how things worked: what was a file? what was a widget? These lines were blurred for users.

Who was "everyone"?

We have the Product meeting and the Mockup discussions calls exactly to discuss this type of decisions. This wasn't a request from Product call as far as I know. And I've used this feature countless times in product demos.

I never agreed to it, nor would because it serves a very specific purpose: When users want to drop a file that is temporary and they want to ask something without it being transformed into a data connector.

In the original RFC, shared over 3 months ago I explicitly highlighted the distinction between "context widgets" and "temporary context":

<img width="765" alt="Screenshot 2024-10-21 at 8 20 34 PM" src="https://github.com/user-attachments/assets/e8d6d7bc-6481-46f7-8dac-a557e80d3960">

It has a very specific purpose, and I never heard users complaining that it's confusing. If anything, I've not tested any AI copilot that doesn't allow the drop of a file on the chat - so that's the norm and not the exception imo.

It was also already implemented...

So let's bring it back please - since I have a very strong opinion on keeping this one.

PS: One of the demos I use it for is to drop an image and ask copilot to extract data. Then I create a table widget from it, and render it as a chart. I effectively have a widget table/chart as a result that is interactive - as opposed to a screenshot. If I can't drop a file on the chat I would go through all of this and then have to remove the file from data connectors when I didn't want it there in the first place.

2024-10-23 20:01 UTC, DidierRLopes approved these changes

2024-10-24 07:30 UTC, merged